openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /greet:
    post:
      tags:
      - rest-api
      operationId: greet
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /:
    get:
      tags:
      - rest-api
      operationId: greet_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
