openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /greet:
    post:
      tags:
      - rest-api
      summary: Returns a response as Hello with a name
      description: This POST operation returns a response as Hello with a given name
      operationId: greet
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: SUCCESS
          content:
            '*/*':
              schema:
                type: string
        "500":
          description: FAILURE
          content:
            '*/*':
              schema:
                type: string
  /:
    get:
      tags:
      - rest-api
      summary: Returns a response as Hello World!
      description: This GET operation returns a response as Hello World!
      operationId: greet_1
      responses:
        "200":
          description: SUCCESS
          content:
            '*/*':
              schema:
                type: string
        "500":
          description: FAILURE
          content:
            '*/*':
              schema:
                type: string
components: {}
